version: '3.8'
services:
  stockMicroservice:
    build:
      dockerfile: ./Dockerfile
      context: ./stock-service
    volumes:
      - ./stock-service/:/var/www/stock-service
    image: node:latest
    container_name: stock-microservice
    ports:
      - "3002:3002"
    networks:
      jobsityNetwork:
        ipv4_address: 192.128.1.5

networks:
  jobsityNetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.128.0.0/16
          gateway: 192.128.0.1
